apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dotnet-web-sample.fullname" . }}
data:
  VariableInObject__Key: "{{ .Values.configMap.valueInObject }}"
  VariableInArray__0: "{{ .Values.configMap.valueInArray_0 }}"
  Variable: "{{ .Values.configMap.value }}"