apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "docker-angular-sample.fullname" . }}
  labels: {{- include "docker-angular-sample.labels" . | nindent 4 }}
data:
  env.json: |-
  {{ toJson .Values.configMap.env | indent 4 }}
