apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: dotnet-web-sample
  name: dotnet-web-sample
  namespace: demo
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: dotnet-web-sample
  type: LoadBalancer
status:
  loadBalancer: {}
