apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: docker-angular-sample
  name: docker-angular-sample
  namespace: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: docker-angular-sample
  strategy: {}
  template:
    metadata:
      labels:
        app: docker-angular-sample
    spec:
      containers:
      - image: k8sworkshop.azurecr.io/docker-angular-sample:latest
        name: docker-angular-sample
        resources: {
        ports: 
          - name: http
            containerPort: 8080
            protocol: TCP
        volumeMounts:
            - name: env-config
              mountPath: /usr/share/nginx/html/assets/env/env.json
              subPath: env.json
      volumes:
        - name: env-config
          configMap:
            name: docker-angular-sample
status: {}
