apiVersion: v1
kind: Service
metadata:
  labels:
    app: docker-angular-sample
  name: docker-angular-sample
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: docker-angular-sample
  type: LoadBalancer
status:
  loadBalancer: {}
